# Generated by Django 5.2.17 on 2026-09-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberBreachData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('records', models.CharField(max_length=255)),
                ('org_type', models.CharField(max_length=255)),
                ('methods', models.CharField(max_length=255)),
                ('add_data_val', models.CharField(blank=True, max_length=255, null=True)),
                ('time_val', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
