# Generated by Django 5.2.17 on 2026-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberbreachdata',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
