# Generated by Django 5.2.17 on 2026-09-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_course_userregistration_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='password',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
