# Generated by Django 5.2.17 on 2026-09-16 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_userregistration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='gender',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='passward',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
