# Generated by Django 5.2.17 on 2026-09-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_userregistration_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='passward',
            new_name='password',
        ),
    ]
