# Generated by Django 5.2.17 on 2026-09-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_passward_userregistration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
