# Generated by Django 5.2.17 on 2026-09-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_userregistration_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
